# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 054ebaa5c3dae8327e85aac3109060d4dcbbbd704130aaf85fc24f56e885e73cf8d8697f46d344f2f8721082bc9cffc6af427b4cc358a5dc591f02665ddc0eb9

test:
  secret_key_base: 35773a3627f916145ac7a440301b1782216ec01b6405cc1ea46b181e0814790688d77cf36abb4c9c6ef417b0c1348de1cb2897f772faea6ae6134f1967398c82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
